language: node_js
node_js:
- 5.3
addons:
  sauce_connect: true
install: npm install -production
env:
  global:
  - secure: ByZfVZx2qofiMljteBgF6YpMxQzuB1TJNz2QfoNmUp7fZoopZz9fCItlmUNuecrGXCmVW720KVyZW+4FyVS07c7aX3Q6kKLB2hhJTIgOunkQuVmMdjmAl/xrNW0JuNhrq2bKJg0b1qOa9VDqB8kHkh9383EQB2HYCU+QLiXmKvNcebN8OIi9DI+5F50GPVon/5eokQD8eX8LViCl0cr1OGqbwEn6GFBb8u/bx80tqECfMUQzYP/JSmG7rLGXUgJdP4bQ+tneNigdvythgPZtWT0l3VBPtB98lE77FQpkMHLUO93YsQ/HljvF35QkOQipZpJQC5SmsQZv+FtTAeVTeX7DKaQg/n4DfxjQOT5k1LjLMaZm7JZc51TlQ+SA0r8QPwBTZgT5Zpsu4ushfDcQ7D9RlVkRhAswiXugCw5+yxzht9WGc3eT1Ffh/k11v++tp+rZIjpI2H15OnYQ/NykCTD7q7sGJsTCss5biwirzFnku3QuWEo1qAIU9vVtOgoxm9L69aS+AfTPxumJFvO/XCF13/MZJjpEFfKlKjuA8JSfBZ3f1KzmVKpqte49N2qq11l5WIPNMQq/dWibHjdyVmC0o9tsOvRjxqe5NEQeZhkGB4biksyWIyS7ErMxlAf8Eev07aMD8KDTv5tiEOKEqWTCkf1nOqyvrz0QqQvs4t8=
  - secure: ZBj1LoZ9tjGmZOFc3O3Sc8sZbJL00SfW/pnXxeJKnvAe78TrJneBPC7YuRP8jyvZ+FhVC2g/C098yH3qiQwbFIg37uv3GkesJrdfOlCDRQl/h6fXiDUWAfhXg6NePDT6MfeXS6cNK+xQW7JBZEgwkNIGRBbwUOVqm3nqROLI4ZtMdPGVXla5P/uhJEpV9hCTiAFBQujrwKM1uz0IZMpS5tdylUQSSvmdWCD0g29yFmvEoOH6G66rbNh6tPCXyW523aXt8Wkc9I8vV9t62oJ86nNCFUdq/cfrILwT59ESDFK0Sxgs4cEIGSfO7BAWFxH5WcbVUdrrYPoxp4L73+Y5G7DLef9gJGGbYmvKlfAvs8TfcBqdyg0hYfSSAcP1bOKhuw9J+xMtWuO8XMLkmNBkeYjD9l49i6o3kaDurPVtL/Kl/bV0+WfLm+bDTOfGdAh6E44uQQforO2wgD7SSta52XK/WZPC5ZZl4iYf/NcpnJPHsRkpuowF5V494uHYAoVzMQfmPfCbAzFk0b4D0jK7OlctcFHksfllbGthyYS1VadOCjvz1Fl68eaU0p3RBO64WRshFefylnLy5tHXQ+bdNsL+VTjosUfp6r0poP7iIZbQQfi0KCqrI5h3euQrws0b5Mj/NzrIVt08/w9gbegmWrf4/Icd3Tu8PEoJ+QxQv04=
deploy:
  provider: s3
  access_key_id: AKIAIUIUGGLNVZ3DGALQ
  secret_access_key:
    secure: qkxF1mfpNFXPaEsGleevYqN8cD+wPEYxx4VavMhB6YVWbvW4T9xCiYdZPGitauuHU4IZPt2ILPe26kPpB2B6Af7eFJXSHAEBNShSJRIE2Itg/XlDFNIpEE+ZL33vnQL1bB3UPV6WFwOs1mmJgHxd5N5kyFpnjrBPqzTF5HX3yWO2cIOuHRvQQB9bFPxL8tCDXAmEjS0zZpMs7LhIZ4x4WOV27lSzaFvBP5Vh/Ge/hekS/LwDYcmNS2aetFmRFQTRNGM5LvmFgKD4xbF5vOSE5KnNhZF+qd6ujXRX5hLpakf6AH28Q9zKWltls7BCcQxVewEWpHu5tKHUrgh+sWcEjUv+w/YQ/yQvv1/2wj6RHFzcqbV4GTqB+i4X/U8yJRbSFdzoeUwHyFaLJ8fVsmTHwIh+kf6lay87bkqf/PJ0nDzWdjBOaY6HIQ/ngWaQgi+RRcHsJvlZ3LjT4vwzhY7EQeLlL139xutfCbX9GmdCpHiz0V82myS1ZB8JsUPAcrormoPvht7h/5dW9FUrJUDrBUMuDpx1aNuMzdYQQUvvZPPzA99L1yK6PIgpg7nXj5rqIqy/N9Py34JycYgBQeJYuHWkzDF9ZiTapkfviGYyQZ25rmvbps/BRO87OavpeuzRJczeEKdSgeKCh+6twgs16CWmVF1hqziIKTdKnRoKx0U=
  bucket: dcypherthis-test-reports
  skip_cleanup: true
  local-dir: ./reports/
  upload-dir: travis-builds
  on:
    repo: dcypherthis/wdio-boilerplate-cucumber
    branch: feature/s3-reports-upload
