hub:
  image: selenium/hub
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox
  links:
    - hub
chrome:
  image: selenium/node-chrome
  links:
    - hub
# firefox-debug:
#   image: selenium/node-firefox-debug
#   ports:
#       - "5900:5900"
#   links:
#     - hub
# chrome-debug:
#   image: selenium/node-chrome-debug
#   ports:
#       - "5901:5901"
#   links:
#     - hub
